annotations:
  min_scale_version: 24.10.2.2
app_version: 1.0.0-beta
capabilities: []
categories:
- financial
changelog_url: https://github.com/deltabadger/deltabadger/releases
date_added: '2026-01-13'
description: Auto-DCA bot for cryptocurrency. Automate your Dollar Cost Averaging
  strategy across multiple exchanges.
home: https://github.com/deltabadger/deltabadger
host_mounts: []
icon: https://media.sys.truenas.net/apps/deltabadger/icons/icon.png
keywords:
- crypto
- cryptocurrency
- dca
- bitcoin
- finance
lib_version: 2.1.75
lib_version_hash: 0555788a1ba4810e2636be89bc3cd040abd76ebd98dff9c1b0b086da7a6d42b6
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: deltabadger
run_as_context:
- description: Deltabadger runs as any non-root user.
  gid: 568
  group_name: deltabadger
  uid: 568
  user_name: deltabadger
screenshots: []
sources:
- https://github.com/deltabadger/deltabadger
title: Deltabadger
train: community
version: 1.0.0
